### PR TITLE
17 miscellaneous fixes

### LINKED ISSUE #17: Miscellaneous fixes
- Fix server response actions
- Fix signup 
- Add message toasts

### PR DESCRIPTION
**Pull request by rdshinde**
Refactor and miscellaneous fixes.

### CODE REVIEW

**Review by junaidshaikh-js — APPROVED** [review]
Everything looks good, can be merged.

File: src/components/filter/Filter.jsx [hunk 1]
```diff
@@ -205,48 +205,31 @@ export const Filter = () => {
...
-            </label>
-          </div>
+          {[
+            { displayName: "Men", categoryName: "MEN" },
+            { displayName: "Women", categoryName: "WOMEN" },
+            { displayName: "Boys", categoryName: "BOYS" },
+          ].map(({ displayName, categoryName }) => {
+            return (
+              <div className="input-group">
+                <label hrmlFor="popular">
```
Comment (sadathshariff) [inline src/components/filter/Filter.jsx]: typo here htmlFor

**Review by sadathshariff — APPROVED** [review]
Overall Looks good suggested a point have a look
